spring:
  application:
    name: springboot-developer
  jpa:
    # \uC804\uC1A1 \uCFFC\uB9AC \uD655\uC778
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # \uD14C\uC774\uBE14 \uC0DD\uC131 \uD6C4\uC5D0 data.sql \uC2E4\uD589
    defer-datasource-initialization: true