spring:
  application:
    name: springboot-developer
  jpa:
    # show sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # data.sql
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true

jwt:
  issuer: pro9735@naver.com
  secret_key: study-springboot
